# Generated by Django 5.1.4 on 2025-01-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_id', models.CharField(max_length=20)),
                ('produto_name', models.CharField(max_length=100)),
                ('produto_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto_qnd_est', models.PositiveIntegerField()),
                ('produto_dt_cri', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
